# Generated by Django 4.1.2 on 2022-11-23 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_title', message='A chamada do banner deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: Banner de promoção', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Chamada do banner')),
                ('description', models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_description', message='A descrição do banner deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: Aqui você tem garantia de estar adquirindo máquinas agrícolas de alta tecnologia, qualidade e resistência.', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Descrição do banner')),
                ('link', models.URLField(validators=[django.core.validators.URLValidator(code='invalid_link', message='O link do botão deve conter http:// ou https://', regex='^(http|https)://')], verbose_name='Link do botão')),
                ('image', models.ImageField(upload_to='banners/home', validators=[django.core.validators.validate_image_file_extension], verbose_name='Imagem do banner')),
            ],
            options={
                'verbose_name_plural': 'Banners do Site',
            },
        ),
    ]
