# Generated by Django 4.1.2 on 2022-11-23 18:49

import autoslug.fields
import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='O nome do produto deve conter apenas letras, números e espaços. Ex: Meridia 200', regex='^[/\\"\'a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)], verbose_name='Nome do produto')),
                ('code', models.CharField(default='Não informado', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_code', message='O código do produto deve conter apenas letras, números e espaços. Ex: 001MSO345', regex='^[0-9]+$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)], verbose_name='Código do produto')),
                ('branding', models.CharField(default='Não informado', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_branding', message='A marca do produto deve conter apenas letras, números e espaços. Ex: Jacto', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)], verbose_name='Marca do produto')),
                ('cover', models.ImageField(default='', unique=True, upload_to='covers/parts', verbose_name='Capa do produto')),
                ('description', ckeditor.fields.RichTextField(max_length=2000, verbose_name='Descrição do produto')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.family', verbose_name='Qual a família do produto?')),
                ('model_version', models.ManyToManyField(blank=True, to='categories.modelsandversions', verbose_name='Modelo/versão')),
                ('subfamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subfamily', verbose_name='Qual a subfamília do produto?')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.FILER_IMAGE_MODEL)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parts.parts')),
            ],
        ),
    ]
