# Generated by Django 4.1.2 on 2022-10-26 13:17

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Produto')),
                ('branding', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca do produto')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição do produto')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.family', verbose_name='Qual a família do produto?')),
                ('model_version', models.ManyToManyField(blank=True, to='categories.modelsandversions', verbose_name='Modelo/versão')),
                ('subfamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subfamily', verbose_name='Qual a subfamília do produto?')),
            ],
            options={
                'verbose_name_plural': 'Peças',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.FILER_IMAGE_MODEL)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parts.parts')),
            ],
        ),
    ]
