# Generated by Django 4.1.2 on 2022-11-23 18:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', ckeditor.fields.RichTextField(verbose_name='Descrição do produto')),
                ('image_file', filer.fields.image.FilerImageField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='products.product')),
            ],
            options={
                'verbose_name': 'Bloco de texto',
                'verbose_name_plural': 'Blocos de texto',
            },
        ),
    ]
