# Generated by Django 4.1.2 on 2022-11-23 18:49

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Useds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Nome do produto inválido, apenas letras, números e espaços', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Nome do produto')),
                ('branding', models.CharField(max_length=100, verbose_name='Marca do produto')),
                ('description', models.TextField(max_length=2000, verbose_name='Descrição do produto')),
                ('cover', models.FileField(blank=True, null=True, unique=True, upload_to='covers', verbose_name='Capa do produto')),
                ('model', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid', message='Modelo do produto é inválido. Apenas letras e números.', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Modelo do produto')),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='invalid', message='Ano do produto é inválido. Ex: 2020', regex='^[0-9]{4}$')], verbose_name='Ano do produto')),
                ('price', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Preço do produto é inválido. Ex: R$600.000,00', regex='^R\\$\\d{1,4}(\\.\\d{3})*,\\d{2}$')], verbose_name='Preço do produto')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Usado',
                'verbose_name_plural': 'Usados',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='useds.useds')),
                ('image_url', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_used', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
