# Generated by Django 4.1.2 on 2022-11-23 18:49

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='O nome da categoria deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: Máquinas Agrícolas', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Nome da categoria')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cultures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='O nome da cultura deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: Soja', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Nome da cultura')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Culturas',
            },
        ),
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='A disponibilidade deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: Em estoque', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Disponibilidade')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Disponibilidade',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='O nome da família deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: Pulverizadores Automotrizes', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Nome da família')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Famílias',
            },
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='O lançamento deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: 2020', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Lançamento')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Lançamentos',
            },
        ),
        migrations.CreateModel(
            name='ModelsAndVersions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='O modelo ou versão do produto deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: 1000', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Qual o modelo ou versão do produto?')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Modelos e versões',
            },
        ),
        migrations.CreateModel(
            name='SizeOfArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='O tamanho da área deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: Até 500 hectares', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Tamanho da área')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tamanho da área',
            },
        ),
        migrations.CreateModel(
            name='SubFamily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='O nome da subfamília deve conter apenas letras, números, espaços, vírgulas, pontos, hífens e sublinhados. Ex: Bicos de Pulverização', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Nome da subfamília')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Subfamílias',
            },
        ),
    ]
