# Generated by Django 4.1.2 on 2022-11-23 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consortium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_name', message='O nome deve conter apenas letras e espaços. Ex: João da Silva', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Nome completo')),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_email. Ex: sample@gmail.com', message='O e-mail deve ser válido', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')], verbose_name='E-mail')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(15), django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_phone', message='O telefone deve ser válido. Ex: 11 99999-9999', regex='^\\d{2}\\d{4,5}\\d{4}$')], verbose_name='Telefone')),
                ('state', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_state', message='O estado deve conter apenas letras e espaços. Ex: São Paulo', regex='^[a-zA-Zà-úÀ-Ú\\s]+$')], verbose_name='Estado')),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_city', message='A cidade deve conter apenas letras e espaços. Ex: São Paulo', regex='^[a-zA-Zà-úÀ-Ú\\s]+$')], verbose_name='Cidade')),
                ('product_request', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto selecionado')),
                ('accept_contact', models.BooleanField(default=True, verbose_name='Aceita receber contato?')),
            ],
            options={
                'verbose_name_plural': 'Dados do Consórcio',
            },
        ),
    ]
