# Generated by Django 4.1.1 on 2022-10-17 11:41

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('branding', models.CharField(max_length=100, verbose_name='Marca do produto')),
                ('description', models.TextField(verbose_name='Descrição do produto')),
                ('cover', models.FileField(blank=True, null=True, unique=True, upload_to='covers', verbose_name='Capa do produto')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo do produto')),
                ('year', models.CharField(max_length=100, verbose_name='Ano do produto')),
                ('price', models.CharField(max_length=100, verbose_name='Preço do produto')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Usados',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='used.used')),
                ('image_url', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_used', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
