# Generated by Django 4.1.2 on 2022-10-26 13:17

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('description', models.TextField(blank=True, max_length=130, null=True, verbose_name='Promessa do produto')),
                ('link', models.URLField(verbose_name='Link para o produto')),
                ('image', models.ImageField(upload_to='public/featured', verbose_name='Imagem do produto')),
            ],
            options={
                'verbose_name_plural': 'Produtos em Destaque',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('promise', models.CharField(blank=True, max_length=100, null=True, verbose_name='Promessa')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição do produto')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('cover', models.FileField(blank=True, null=True, unique=True, upload_to='public/covers', verbose_name='Capa do produto')),
                ('launch', models.BooleanField(default=False, verbose_name='É lançamento?')),
                ('flyer', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Link do folheto')),
                ('youtube', models.URLField(blank=True, null=True, unique=True, verbose_name='Possui vídeo no youtube?')),
                ('area', models.ManyToManyField(blank=True, to='categories.sizeofarea', verbose_name='Qual o tamanho da área?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Qual a linha do produto?')),
                ('cultures', models.ManyToManyField(blank=True, to='categories.cultures', verbose_name='Qual a cultura?')),
                ('disponibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.disponibility', verbose_name='Disponibilidade')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
