# Generated by Django 4.1.2 on 2022-11-23 18:49

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='O nome do produto deve conter apenas letras, números e espaços. Ex: Meridia 200', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Nome do produto')),
                ('promise', models.CharField(blank=True, max_length=116, null=True, validators=[django.core.validators.RegexValidator(code='invalid_promise', message='A promessa deve conter apenas letras, números e espaços. Ex: Robustez e qualidade para o seu Plantio.', regex='^[/!?a-zA-Zà-úÀ-Ú0-9\\s\\,\\.\\-\\_]+$')], verbose_name='Promessa')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/products', verbose_name='Capa do produto')),
                ('launch', models.BooleanField(default=False, verbose_name='É lançamento?')),
                ('featured', models.BooleanField(default=False, verbose_name='Quer destacar este produto?')),
                ('flyer', models.URLField(blank=True, max_length=300, null=True, validators=[django.core.validators.URLValidator(code='invalid_flyer', message='O link do folheto deve começar com http:// ou https://', regex='^(http|https)://')], verbose_name='Link do folheto')),
                ('youtube', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(code='invalid_youtube', message='O link do vídeo deve começar com http:// ou https://', regex='^(http|https)://')], verbose_name='Possui vídeo no youtube?')),
                ('area', models.ManyToManyField(to='categories.sizeofarea', verbose_name='Qual o tamanho da área?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Qual a categoria do produto?')),
                ('cultures', models.ManyToManyField(to='categories.cultures', verbose_name='Qual a cultura?')),
                ('disponibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.disponibility', verbose_name='Disponibilidade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.FILER_IMAGE_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
